export const START_LIST_LOAD = "START_CONVERSATION_LIST_LOAD";
export const STOP_LIST_LOAD = "STOP_CONVERSATION_LIST_LOAD";
export const UPDATE_LIST = "UPDATE_CONVERSATION_LIST";
export const INSERT_NEW_CONVERSATION = "INSERT_NEW_CONVERSATION";
export const INSERT_OLD_MESSAGES = "INSERT_OLD_MESSAGES";
export const INSERT_NEW_MESSAGE = "INSERT_NEW_MESSAGE";
