export const START_LIST_LOAD = "START_NEWS_EDIT_LIST_LOAD";
export const STOP_LIST_LOAD = "STOP_NEWS_EDIT_LIST_LOAD";
export const UPDATE_LIST = "UPDATE_NEWS_EDIT_LIST";
export const START_SAVE_LOAD = 'START_NEWS_EDIT_SAVE_LOAD';
export const STOP_SAVE_LOAD = 'STOP_NEWS_EDIT_SAVE_LOAD';
export const START_ITEM_ACTION_LOAD = 'START_NEWS_EDIT_ITEM_ACTION_LOAD';
export const STOP_ITEM_ACTION_LOAD = 'STOP_NEWS_EDIT_ITEM_ACTION_LOAD';