export const START_LIST_LOAD = "START_GROUP_CONVERSATION_LIST_LOAD";
export const STOP_LIST_LOAD = "STOP_GROUP_CONVERSATION_LIST_LOAD";
export const UPDATE_LIST = "UPDATE_GROUP_CONVERSATION_LIST";
export const INSERT_NEW_CONVERSATION = "INSERT_NEW_GROUP_CONVERSATION";
export const INSERT_OLD_MESSAGES = "INSERT_OLD_GROUP_MESSAGES";
export const INSERT_NEW_MESSAGE = "INSERT_NEW_GROUP_MESSAGE";
export const DECREMENT_COUNT_NEW_MESSAGE = "DECREMENT_COUNT_NEW_GROUP_MESSAGE";