export const START_LIST_LOAD = "START_CHAT_USERS_LIST_LOAD";
export const STOP_LIST_LOAD = "STOP_CHAT_USERS_LIST_LOAD";
export const UPDATE_LIST = "UPDATE_CHAT_USERS_LIST";
export const INSERT_NEW_CHAT_USER = "INSERT_NEW_CHAT_USER";